### PR TITLE
Add counter test

### PR DESCRIPTION
**Pull request by rudicarrilloypr**
- [x] - Add test function for items counter, covered with unit tests using Jest.

### CODE REVIEW

**Comment by rudicarrilloypr** [comment]
TESTS CHECKED ✅
Captura de pantalla 2023-07-05 a la(s) 20 28 24

**Comment by Grandi0z** [comment]
Hi brother, I had a little problem with the test when I tried I got this error : `Cannot find module 'jest-fetch-mock' from 'src/tests/pokemonCounter.test.js'` 
as in the attached screenshot
testV

**Comment by Grandi0z** [comment]
I'm sorry for that but we missed something in the last pull request. I just noticed that the number of likes changes on Pokemon each time we load the page.
Here are 2 screen-shot of the first and the second load.
I think you should use an ID to attach the number of likes to 
pokemon2
a specific Pokemon
pokemon1

**Comment by rudicarrilloypr** [comment]
> I'm sorry for that but we missed something in the last pull request. I just noticed that the number of likes changes on Pokemon each time we load the page. Here are 2 screen-shot of the first and the second load. I think you should use an ID to attach the number of likes to pokemon2 a specific Pokemon pokemon1

hey bro! it is because everytime you refresh the page it changes of position the pokemon, that's how the API works, if you can see in your screenshot on each image the pokemon is different, but if you look for the same pokemon name on the page it has the same number of likes, so the page works

**Comment by rudicarrilloypr** [comment]
> Hi brother, I had a little problem with the test when I tried I got this error : `Cannot find module 'jest-fetch-mock' from 'src/tests/pokemonCounter.test.js'` as in the attached screenshot testV

oh it is because you have to install the jest-fetch-mock dependency in your computer, just run **npm install** bro

**Comment by Grandi0z** [comment]
@rudicarrilloypr Thank you. Everything is clear now

**Comment by Grandi0z** [comment]
## Hello @rudicarrilloypr 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

**Pull request merged**
